# Buildspec for Container 1
# File: buildspec-container1.yml
version: 0.2

phases:
  build:
    commands:
      - docker build -t e2e-boilerplate/demoapp .
      - docker push demoapp

# Buildspec for Container 2
# File: buildspec-container2.yml
# version: 0.2

# phases:
#   build:
#     commands:
#       - docker build -t data/sql .
#       - docker push data/sql

# # Buildspec for Container 3
# # File: buildspec-container3.yml
# version: 0.2

# phases:
#   build:
#     commands:
#       - docker build -t e2e-test .
#       - docker push e2e-test
