# Buildspec for Container 1
# File: buildspec-container1.yml
# version: 0.2

# phases:
#   build:
#     commands:
#       - docker build -t e2e-boilerplate/demoapp demoapp/.
#       - docker push e2e-boilerplate/demoapp
version: 0.2

phases:
  install:
     runtime-versions:
        nodejs: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build --tag $AWS_IMAGE_DEMO_APP:latest demoapp/.
      - ./build-docker-compose.sh
      - npm i -D playwright
      - npx playwright install
      - docker compose -f docker-compose-cicd.yml run -t -d test
      - docker tag $AWS_IMAGE_DEMO_APP:$AWS_IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_DEMO_APP:$AWS_IMAGE_TAG

      # - docker build --tag  demoapp:latest demoapp/.
      # - docker tag demoapp:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/demoapp:latest

      # - docker build --tag  $AWS_IMAGE_TEST:latest e2e-test/.
      # - docker tag $AWS_IMAGE_TEST:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_TEST:latest

      # - docker build --tag  test-e2e:latest e2e-test/.
      # - docker tag  test-e2e:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/test-e2e:latest

      # - docker build --tag mssql:latest data/sql/.
      # - docker tag mssql:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mssql:latest

      # - docker build --tag  $AWS_IMAGE_MSSQL:latest data/sql/.
      # - docker tag $AWS_IMAGE_MSSQL:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_MSSQL:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_DEMO_APP:$AWS_IMAGE_TAG

      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_TEST:latest

      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$AWS_IMAGE_MSSQL:latest

      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/test-e2e:latest

      # - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/mssql:latest

