version: '3.8'
services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    platform: linux/amd64
    ports:
      - 1433:1433
    volumes:
      - /var/opt/mssql
      # we copy our scripts onto the container
      - ./data/sql/volume:/usr/src/app 
    # bash will be executed from that path, our scripts folder
    working_dir: /usr/src/app 
    # run the entrypoint.sh that will import the data AND sqlserver
    command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Passw@rd2022
  web:
    build:
      context: ./demoapp
      target: runner
    depends_on:
      - mssql
    command: npm run start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DBHOST: mssql
    
