AWSTemplateFormatVersion: '2010-09-09'
Resources:
  RDSServiceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: RDS-Service-Role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - rds.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        - PolicyName: RDS-Service-Policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'rds:CreateDBInstance'
                  - 'rds:ModifyDBInstance'
                  - 'rds:DeleteDBInstance'
                  - 'rds:DescribeDBInstances'
                Resource: '*'
  RDSInstance:
    Type: 'AWS::RDS::DBInstance'
    Properties:
      AllocatedStorage: 100
      BackupRetentionPeriod: 7
      LicenseModel: license-included
      Engine: sqlserver-se
      EngineVersion: 15.00.4312.2.v1
      DBInstanceClass: db.m5.large
      MasterUsername: admin
      MasterUserPassword: Password123
      MultiAZ: false
      PubliclyAccessible: true
      StorageType: gp2
      VPCSecurityGroups:
        - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
    Metadata:
      'AWS::CloudFormation::Init':
        config:
          commands:
            01_associate_role:
              command: aws rds add-role-to-db-instance --db-instance-identifier !Ref RDSInstance --role-arn !Ref RDSServiceRole
              env:
                AWS_DEFAULT_REGION: !Ref 'AWS::Region'


  DBSubnetGroup:
    Type: 'AWS::RDS::DBSubnetGroup'
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS SQL Server
      SubnetIds:
        - subnet-c7133c8e 
        - subnet-01ddef66 # Replace with your subnet IDs

  DBSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: RDS SQL Server security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 1433
          ToPort: 1433
          CidrIp: 0.0.0.0/0
      VpcId: vpc-5cc68c3b  # Replace with your VPC ID
Outputs:
   SQLDatabaseEndpoint:
     Description: Database endpoint
     Value: !Sub "${RDSInstance.Endpoint.Address}:${RDSInstance.Endpoint.Port}"
  
